# Generated by Django 5.2.4 on 2025-08-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payment_paid_payment_message_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cart_items',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
