# Generated by Django 5.2.4 on 2025-08-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cart_items',
            field=models.JSONField(default=dict),
        ),
    ]
