# Generated by Django 5.2.4 on 2025-08-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='message',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='initialized', max_length=100),
        ),
    ]
