# Generated by Django 5.2.4 on 2025-08-17 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_payment_message_alter_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cart_items',
        ),
    ]
