# Generated by Django 5.2.4 on 2025-08-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_remove_payment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cart_items',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='message',
            field=models.JSONField(default=dict),
        ),
    ]
