# Generated by Django 5.2.4 on 2025-08-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='another',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
