# Generated by Django 5.2.4 on 2025-08-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_customuser_xxx_customuser_another'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='another',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
