# Generated by Django 5.2.4 on 2025-08-05 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_customuser_another_remove_customuser_xxx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='xxx',
        ),
    ]
