# Generated by Django 5.2.4 on 2025-08-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_customuser_xxx'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='immages',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
