# Generated by Django 5.2.4 on 2025-08-05 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_course_immages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='immages',
            new_name='images',
        ),
    ]
