# Generated by Django 5.2.4 on 2025-08-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_immages_course_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='images',
            field=models.CharField(blank=True, default='summer-camp.jpg', max_length=200, null=True),
        ),
    ]
