# Generated by Django 5.2.4 on 2025-08-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='paid_amount',
        ),
        migrations.AddField(
            model_name='cart',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
